import python31 as p3
from python31 import Test as t3
import sys

print('Python', sys.version)

print('\ntiming range()')

print('Python', sys.version)
print('Hello, World!')

print("some text,", end="")
print(' print more text on the same line')

print('Python', sys.version)
print('3 / 2 =', 3 / 2)
print('3 // 2 =', 3 // 2)
print('3 / 2.0 =', 3 / 2.0)
print('3 // 2.0 =', 3 // 2.0)

print('Python', sys.version)
print('strings are now utf-8 \u03BCnico\u0394Ã©!')

print('and Python', sys.version, end="")

print('Python', sys.version)
try:
    let_us_cause_a_NameError
except NameError as err:
    print(err, '--> our error message')

p3.test_range(10)

t31 = t3()

t31.Do("Heyyyy")
